"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var inversify_1 = require("inversify");
var types_1 = require("./types");
var entities_1 = require("./entities");
var container = new inversify_1.Container();
exports.container = container;
container.bind(types_1.TYPES.Warrior).to(entities_1.Ninja);
container.bind(types_1.TYPES.Weapon).to(entities_1.Katana);
container.bind(types_1.TYPES.ThorwableWeapon).to(entities_1.Shuriken);
